### ISSUE TITLE
Invalid get_string() identifier: 'cachedef_backup' 

### ISSUE THREAD

**Issue by ewallah** [leblangi/moodle-tool_purgeautobackups#1]
When reviewing the cache administration (cache/admin.php), an error is generated:

Invalid get_string() identifier: 'cachedef_backup' or component 'tool_purgeautobackup'. Perhaps you are missing $string['cachedef_backup'] = ''; in .../admin/tool/purgeautobackup/lang/en/tool_purgeautobackup.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 9459 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 9493 of /lib/moodlelib.php: call to lang_string->get_string()
line ? of unknownfile: call to lang_string->__toString()
line 212 of /lib/classes/collator.php: call to Collator->asort()
line 322 of /lib/classes/collator.php: call to core_collator::asort()
line 238 of /cache/renderer.php: call to core_collator::asort_array_of_arrays_by_key()
line 303 of /cache/admin.php: call to core_cache_renderer->definition_summaries()

**Comment by leblangi** [comment]
Thanks for reporting this. The master branch is now fixed.
